name: Docker Image CI

on:
  schedule:
  - cron: '33 3 3 * *'
  workflow_dispatch:
    
env:
  USER_EXTENSION: "gd pdo_mysql"
  
jobs:

  build:

    runs-on: ubuntu-latest
    name: Build and push Docker images
    
    strategy:
      fail-fast: false
      matrix:
        php-version: [7.4, "8.0"]

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3     
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2.7.0
        with:
          context: ${{ matrix.php-version }}
          build-args: "user_extension=${{ env.USER_EXTENSION }}"
          no-cache: true
          push: true
          tags: ${{ github.actor }}/php-fpm:${{ matrix.php-version }}-fpm-alpine
